    </div>
    </td>
    <td>
      <div class="menutableright">
        <?php
        if (0) {#$_SESSION["sidebar_enabled"]) {
	        print "<!-- menu is in the sidebar -->";
        } else {
	        print NewMenu();
        }
          ?>
      </div>
    </td>
  </tr>
</table>

<div class="footer">
    &copy; <a href="http://tincan.co.uk" target="_tincan" class="urhere">tincan limited</a> | <span class="urhere"><?php echo NAME?> powered by </span><a class="urhere" href="http://www.phplist.com" target="_blank">phplist</a> - version <?=VERSION?>
</div>

</div>

</body>
</html>
